In [1]:
import numpy as np
import math
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
x = len(a)
v = a
u = np.zeros((x,1))
print(u)

[[0.]
 [0.]
 [0.]
 [0.]]


In [3]:
for i in range(x):
    u[i] = math.exp(v[i])
    
print(u)

[[ 2.71828183]
 [ 7.3890561 ]
 [20.08553692]
 [54.59815003]]


In [4]:
v_vectorized = np.exp(v)
v_vectorized

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [5]:
A = np.asarray([
    [1,2,3],
    [2,3,4],
    [4,5,6]
])

print(A)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [6]:
cal = np.sum(A, axis=0)
cal

array([ 7, 10, 13])

In [7]:
cal = cal.reshape(1,3)
cal

array([[ 7, 10, 13]])

In [8]:
test = A / cal
test

array([[0.14285714, 0.2       , 0.23076923],
       [0.28571429, 0.3       , 0.30769231],
       [0.57142857, 0.5       , 0.46153846]])

In [9]:
A


array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [10]:
test_v_vertical = np.asarray([
    [1],
    [2],
    [3]
])

test_1 = A+test_v_vertical
test_1

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
test_v_hor = np.asarray([
    [1,2,3]
])

test_2 = A+test_v_hor
test_2

array([[2, 4, 6],
       [3, 5, 7],
       [5, 7, 9]])

In [12]:
test_3 = A / test_v_vertical
test_3

array([[1.        , 2.        , 3.        ],
       [1.        , 1.5       , 2.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [13]:
test_v_hor

array([[1, 2, 3]])

In [14]:
a = test_v_hor
a = a.reshape(1,3)
a

array([[1, 2, 3]])

In [15]:
a = a.reshape(3,1)
a

array([[1],
       [2],
       [3]])

In [16]:
a = a.reshape (3,1)
a

array([[1],
       [2],
       [3]])

In [17]:
a

array([[1],
       [2],
       [3]])

In [18]:
sss = np.sum(a)
sss

6

In [19]:
hori = np.asarray([
    [1,2,3]
])

hori

array([[1, 2, 3]])

In [20]:
for i in range(len(hori)):
    hori[i] = hori[i]*2
    
hori

array([[2, 4, 6]])